# -*- coding: utf-8 -*-
"""PROYECTO-01-FIERRO-DAVID.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aTMTbHRGxuZYAmj5Xaem4APR2rBES1qX
"""

# Commented out IPython magic to ensure Python compatibility.
#Importar librerias
import numpy as np #Con esto importamos la librería numpy
import pandas as pd #Con esto importamos la librería pandas

#Visualización
import matplotlib.pyplot as plt #Con esto importamos la librería matplotlib
import seaborn as sns #Con esto importamos la librería matplotlib

# %matplotlib inline

#Leer el data set
df = pd.read_csv ('/content/country-income.csv')
df.head() #Aquí solo visualizo los datos antes de empezar a trabajar con ellos

df.info()

"""Describir el número de columnas y filas en las cuáles encuentras valores nulos o perdidos y cuántos"""

#Encontrar si hay valores nulos usando la función .info()
df.info()

"""Con el uso de df.info() podemos darnos cuenta que no hay valores nulos, sin embargo, usaremos otra función para verificarlo"""

#Comprobación de no valores nulos
df.isna()

"""Como es posible observar con las mediante las funciones utilizadas anteriormente, no existen valores nulos en este dataset por lo que no es necesaria la imputación de valores

Calcula la media, máximo, mínimo y desviación estándar de las columnas con valores numéricos.
"""

# A continuación se muestra el máximo, mínimo y desviación estándar de la columna Age (edad)
#Se utiliza la función .mean() para obtener la media, .max() para el valor máximo, .min() para el valor minimo y .std() para la desviación std
print('Este es el promedio de la columna Age = ', df['Age'].mean())
print('Este es el valor máximo de la columna Age = ', df['Age'].max())
print('Este es el valor mínimo de la columna Age = ', df['Age'].min())
print('Este es la desviación estándar de la columna Age = ', df['Age'].std())

# A continuación se muestra el máximo, mínimo y desviación estándar de la columna Income (ingresos)
#Se utiliza la función .mean() para obtener la media, .max() para el valor máximo, .min() para el valor minimo y .std() para la desviación std
print('Este es el promedio de la columna Income = ', df['Income'].mean())
print('Este es el valor máximo de la columna Income = ', df['Income'].max())
print('Este es el valor mínimo de la columna Income = ', df['Income'].min())
print('Este es la desviación estándar de la columna Income = ', df['Income'].std())

"""Convertir todos los valores categóricos y binarios en numéricos sin alterar la estructura del dataset."""

# A continuación convertiremos los valores de la columna "Región" a valores númericos
from sklearn.preprocessing import LabelEncoder #Aquí se importa la librería sklearn
labelencoderRegion = LabelEncoder()
df['Region'] = labelencoderRegion.fit_transform(df['Region'])
df.head()

# A continuación convertiremos los valores de la columna "Online_Shopper" a valores númericos
df['Online_Shopper'] = labelencoderRegion.fit_transform(df['Online_Shopper'])
df.head()